# Generated by Django 5.1.7 on 2025-03-14 04:19

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='pages/images/')),
                ('seo_title', models.CharField(blank=True, help_text='Title for SEO (optional)', max_length=255)),
                ('seo_description', models.TextField(blank=True, help_text='Meta description for SEO (optional)')),
                ('seo_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO (optional)', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('layout', models.CharField(choices=[('flex', 'Flex'), ('column', 'Column')], default='flex', max_length=10)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS styles')),
                ('width', models.CharField(blank=True, help_text='Width in px or % (e.g., 100%, 500px)', max_length=10)),
                ('height', models.CharField(blank=True, help_text='Height in px or % (e.g., auto, 400px)', max_length=10)),
                ('margin', models.CharField(blank=True, help_text='CSS Margin (e.g., 10px 20px 30px 40px)', max_length=50)),
                ('padding', models.CharField(blank=True, help_text='CSS Padding (e.g., 10px 20px 30px 40px)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
